### ISSUE TITLE
Time field in posts list page merges with that of next post if title is too long

### ISSUE THREAD

**Issue by sandipb** [htr3n/hyde-hyde#102]
In the list of posts(/posts), if the title is too long, then the time of the post doesn't fit on the same line and clashes with the time on the next post.

This also happens if you reduce the width of the browser.

You can also see this happening on your own website. :)

<img width="528" alt="Screen Shot 2019-12-15 at 12 47 34 AM" src="https://user-images.githubusercontent.com/105359/70860297-f1fcd480-1ed4-11ea-8600-d26cc72d5a88.png">

**Comment by sandipb** [comment]
Since the time class is a "float: right", it floats to the next line if it doesn't fit in its own line. Which happens in the title is too long.

**Comment by sandipb** [comment]
Here it is happening on my own site.

<img width="715" alt="Screen Shot 2019-12-15 at 12 53 18 AM" src="https://user-images.githubusercontent.com/105359/70860329-5cae1000-1ed5-11ea-9c11-a6cc6d60a27c.png">

**Comment by htr3n** [comment]
@sandipb thanks for reporting. I'm aware of that issue and haven't time or better ideas to fix apart from making the title as short as possible. What I have done with the theme is to focus on major screen sizes and adjust manually.

**Comment by sandipb** [comment]
Thanks for your reply.

I have managed to find a workaround. This seems to do the trick for me.
```css
ul.posts li {
    clear: both;
}
```
May be a more tighter scope would be safer, but till I find a problem, this seems to be close enough. :)
