### ISSUE TITLE
Left sidebar overflows beyond the page on https://npf.io/

### ISSUE THREAD

**Issue by brimwats** [htr3n/hyde-hyde#103]
At 100% view:

![image](https://user-images.githubusercontent.com/49103046/71478908-ffad3680-27bf-11ea-8a9c-78e65d9949f1.png)

There's no way to scroll down--I can only see the full list if I zoom out to about 75% (reproduced on chrome and brave browsers)

**Comment by htr3n** [comment]
I'm not sure why you are asking about that site: npf.io. Is that a question about `hyde-hyde` or the site `npf.io`? I'm not the owner of that website, and that is a different theme.

**Comment by brimwats** [comment]
well that is bizzare...I'm not sure how I got it posted here. Apologies for that!
