### ISSUE TITLE
Crashes on macOS 10.15

### ISSUE THREAD

**Issue by acgetchell** [htr3n/hyde-hyde#104]
This theme crashes Hugo. The first few lines are:

```
Change of config file detected, rebuilding site.
2019-12-31 17:31:12.754 -0800
libc++abi.dylib: terminating with uncaught exception of type Sass::Exception::OperationError: cwd gone missing
SIGABRT: abort
PC=0x7fff63c017fa m=8 sigcode=0
```

**Comment by htr3n** [comment]
@acgetchell thanks for reporting the issue. Given such limited information, I'm not sure I can reproduct or investigate further on. Would you mind to share more info about your setting, Hugo version, and commands that you used? I suspect some tools missing, e.g. SCSS compiler. Note that, Hugo supports SCSS but only in the extended version (e.g. see https://stackoverflow.com/questions/54057291/how-to-setup-scss-with-hugo).

**Comment by acgetchell** [comment]
@htr3n Thanks for your response. Looks like the latest version of Hugo addressed it!
