### ISSUE TITLE
Theme not rendering locally with Hugo v0.67.0, works with 0.66.0

### ISSUE THREAD

**Issue by saihv** [htr3n/hyde-hyde#109]
I set up a new site with `hugo new site test`, followed the workflow to set up hyde-hyde as a submodule in test/themes and ran `hugo server -D` - but the theme doesn't render when accessing localhost:1313.

![image](https://user-images.githubusercontent.com/2274262/76502849-05e7a200-6402-11ea-84ae-07ca10f0d9ae.png)

But the theme seems to work fine with Hugo 0.66.0.

**Comment by htr3n** [comment]
I haven't had time to test new Hugo version lately. Are you sure everything set up properly for both versions that you tested?

**Comment by nekr0z** [comment]
I can not reproduce this neither on Hugo 0.67.0 nor on Hugo 0.67.1 - everything seems to work as expected.

**Comment by saihv** [comment]
I did a fresh setup of Hugo 0.67.0 and it is working fine now. I originally had the same setup for both versions, guess it may have been something wrong locally. Sorry about that, closing.
