### ISSUE TITLE
Use without 3rd party scripts

### ISSUE THREAD

**Issue by KuenzelIT** [htr3n/hyde-hyde#11]
Hi,

first of all thank you for the theme! I really like the simplicity.

I don't like to use 3rd party scripts or other data on my site. What would be the best way to achieve this?

Thanks!

**Comment by htr3n** [comment]
Hi,
thanks for your kind words. I'm not quite sure that I understood correctly what you meant about  __other data__, so I will try my best.

Most of the third-party scripts are defined in [`layouts/partials/header.html`](https://github.com/htr3n/hyde-hyde/blob/master/layouts/partials/header.html). You can have a look and exclude them as you wish.

Some other things that you might concern:
* GoogleAnalytics is included in [`layouts/_default/baseof.html`](https://github.com/htr3n/hyde-hyde/blob/master/layouts/_default/baseof.html)
* Commenting (e.g. Disqus or GraphComment) and highlighting (e.g. Highlight.js) are only available for a single post (not list of posts), so you might want to alter [`layouts/_default/single.html`](https://github.com/htr3n/hyde-hyde/blob/master/layouts/_default/single.html), especially the footer.
* If you want to change social icons on the left (i.e. the sidebar), go to [`layouts/partials/sidebar.html`](https://github.com/htr3n/hyde-hyde/blob/master/layouts/partials/sidebar.html) and [`layouts/partials/sidebar_social.html`](https://github.com/htr3n/hyde-hyde/blob/master/layouts/partials/sidebar_social.html)

Hope this helps and please let me know if that works out for you. 

I will leave this issue open for a while.

**Comment by KuenzelIT** [comment]
Hey,

with other data I meant css files, images or fonts (and whatever else can be included).

Thank you for listing where I can find those includes. 

So whats the best way to adjust those files and still get updates (if there will be any) without conflicts? Is it best to just fork the repository and pull in new commits?

Thanks for your help!

**Comment by htr3n** [comment]
The best would be to fork the repository and clean up the stuffs as you wish. When you want to update from this repos or any other forks, you can do `git fetch` and review, then do `git merge`.

**Comment by KuenzelIT** [comment]
Hey,

I want to use those files, but I don't want them to be loaded from an external source. It's about privacy and companies like Google not being able to collect data about users visiting my site.

Thanks a lot for your help and the nice theme! :)

**Comment by htr3n** [comment]
Ok, that makes sense. You can just download the CSS, JS and put in the `static` folder, hugo will find them. For GA, you can either omit the GA id in the `config.toml` or just remove its inclusions then.
