### ISSUE TITLE
Font Awesome 5 file is too big

### ISSUE THREAD

**Issue by jmaister** [htr3n/hyde-hyde#119]
The file from Font Awaesome size is 463 KB.
Only about 20 icons are used, so the file size could be reduced.

**Comment by jmaister** [comment]
I tried selecting the icons used for social networks using http://fontello.com
The resulting file is 1KB of CSS plus abound 4KB for each font type (ttf, woff, woff2).

It has an API to reproduce the build of the font file: https://github.com/fontello/fontello#developers-api

**Comment by htr3n** [comment]
Looks nice but `hyde-hyde` still runs reasonably fast for my site `https://htr3n.github.io`. Maybe it's personal preferences to optimise FA. Thanks anyway.
