### ISSUE TITLE
Ability to use a different font

### ISSUE THREAD

**Issue by kakumarabhishek** [htr3n/hyde-hyde#120]
Hello,

Thank you for creating this excellent theme. Can you please help me with using a different font for the generated site? For example, I would like to use the [Raleway font](https://fonts.google.com/specimen/Raleway).

I added the following line to `layouts/partials/header/web-fonts.html`:

``<link href="https://fonts.googleapis.com/css2?family=Raleway&display=swap" rel="stylesheet">``

Where should I specify this font so that the website can use it? Thank you.

**Comment by jmxsy2016** [comment]
Thank you!
Your work is great for making my website, but I have the same issue: how to use a different font.
Thank you your reply!

**Comment by htr3n** [comment]
Open `assets/scss/hyde-hyde/_variables.scss`  and look fir `$root-font-family`
