### ISSUE TITLE
Google Analytics don't colect data

### ISSUE THREAD

**Issue by allysono** [htr3n/hyde-hyde#121]
Hi everybody! 

In my config. toml, I insert my google analytics code but don't collect any data. Do I need to make some additional config?

Thanks!

**Comment by htr3n** [comment]
Hi,
I don't know why it does not work for you. I set up Google Analytics code and it works fine for me.

https://github.com/htr3n/htr3n-blog/blob/534980961ea9e9d03af8617037c275194baff1de/config.toml#L11

**Comment by allysono** [comment]
Thank you! Works fine now! :)
