### ISSUE TITLE
Upstreaming Improvements From My Site

### ISSUE THREAD

**Issue by gary-kim** [htr3n/hyde-hyde#124]
I'm using this theme for my site (<https://garykim.dev>)(repo: <https://github.com/gary-kim/website>). I've had the site for over half a year now and in that time, I've made a few changes and I think it could be nice to upstream some of them.

Things that come to mind right now:
* [Social shortcode](https://github.com/gary-kim/website/blob/master/layouts/shortcodes/social.html)
* [Last updated date](https://github.com/gary-kim/website/blob/master/layouts/partials/page-single/post-meta.html)
* [Per page navigation toggle](https://github.com/gary-kim/website/blob/master/layouts/partials/page-single/post-navigation.html)
* [Matrix ID in social](https://github.com/gary-kim/website/blob/master/layouts/partials/sidebar/social.html)

There are also design changes but I'm not sure about upstreaming those since they are more personal taste.

Anything you'd like as a PR?

**Comment by MarcoIeni** [comment]
I really like that tags are listed in the home page and that when you click on them, posts are filtered, instead of [this](https://www.marcoieni.com/tags/docker/), which is ugly.

**Comment by gary-kim** [comment]
I'd also be happy to upstream that. That was part of the design changes :)

**Comment by MarcoIeni** [comment]
Hi, I don't know if you are interested but take a look at #130

**Comment by htr3n** [comment]
@gary-kim if you can put up some PRs, why not. Thanks.
