### ISSUE TITLE
Look for new maintainers?

### ISSUE THREAD

**Issue by MarcoIeni** [htr3n/hyde-hyde#130]
Hi @htr3n!
First of all thank you for this awesome theme.

There are a lot of issues and pull requests that haven't received feedback from maintainers in months.
I understand that maintaining open source software is really hard and time consuming and maybe you don't have the energy to do it right now.

I am asking if you are open to look for other maintainers that could help to improve this project.
In this case we could add a line on the README that says something like:

```
We are looking for new maintainers, if you are interested, comment on #130
```

Personally I'm not into frontend development, so I am not available.

**Comment by htr3n** [comment]
Hi @MarcoIeni ,

thanks for your kind words and good will. You are totally right that I don't really have much time to invest into `hyde-hyde` lately as I'm currently having a job that needs my full attention.

Nonetheless, starting from a hobby build theme for my own personal blog, with some tweaks and re-structure here and there to fit into my style, I didn't not expect that many of us like and use it. Thanks a lot for that. I did my best to integrate PRs and fix bugs but, to be honest, I don't fully follow Hugo development and not quite fluent with Go and Go template to keep up with all reasonable and kind requrests here.

I think your suggestion is a good idea as I'm always open to any maintainers / collaborators / helpers. Indeed, many of us have just folked this repository and developed it to newer levels with their skills. I think that's also a way of helping given the nature of open source project with open license.

Cheers,
H.

**Comment by vitaly-zdanevich** [comment]
Hi, I want to be the maintainers of this theme - because I do care for this blog https://p.umputun.com

I would like to add the dark theme by using [prefers-color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme).

**Comment by htr3n** [comment]
@vitaly-zdanevich Added you as a collaborator, you should receive an invitation by now.
