### ISSUE TITLE
Pages listed in Home page

### ISSUE THREAD

**Issue by stuzog** [htr3n/hyde-hyde#15]
This code `{{ range (where .Data.Pages "Type" "!=" "page").GroupBy "Section" }}` in `hyde-hyde layouts/index.html` makes content-type "pages" show up on the home page, listed before "posts". 

Was that its intention? I'm new to Hugo, but I thought "!=page" would eliminate pages being listed?

To get posts only to be listed, I had to change it to:

`{{ range (where .Data.Pages "Type" "post").GroupBy "Section" }}`

See <https://diabeticsbc.ca>

**Comment by htr3n** [comment]
Hi @stuzog ,
I could not find the code you mentioned. Is this the relevant code `{{ range (where .Data.Pages "Type" "!=" "about").GroupBy "Section" }}` ? I just want to exclude the "About" page from the list of posts, that's all ;)

**Comment by htr3n** [comment]
I will close this for now. Please reopen it should you still have problems.
