### ISSUE TITLE
Is HTML template possible?

### ISSUE THREAD

**Issue by davede-git** [htr3n/hyde-hyde#17]
Hello,

Thank you for great theme. I would like to ask you if it is possible to get the same template but as pure HTML file? I would like to re-write it to another CMS solution and it would save my time to do it directly from clean files.

Thanks

**Comment by htr3n** [comment]
Hi @davede-git,
thanks for your interest. By pure HTML, do you mean only HTML+CSS+JS without Hugo and Markdown? Then, yes it's doable. Essentially Hugo uses the templates to render Markdown contents to HTML+CSS+JS. In the end, the outcomes are just normal static Web pages.

If you are familiar with templates (e.g. thinking about a "template" as an empty application form to be filled with particular information -- "content"), then it would be easy for you. The starting point would be [`layouts/_default`](https://github.com/htr3n/hyde-hyde/blob/master/layouts/_default) where you can find the main templates.

For example, [`layouts/_default/single.html`](https://github.com/htr3n/hyde-hyde/blob/master/layouts/_default/single.html) will be used for each individual blog post. It uses [`layouts/_default/baseof.html`](https://github.com/htr3n/hyde-hyde/blob/master/layouts/_default/baseof.html) as the basis, and includes the other files. You can just simple copy and paste the content of the corresponding included files. After all, just clean up Hugo code `{{...}}` with little modification (e.g. links to assets), you are good to go.

The same way can be applied to [`layouts/_default/list.html`](https://github.com/htr3n/hyde-hyde/blob/master/layouts/_default/list.html) for a page showing a list of posts. 

Another approach could be, to just render the content using Hugo and then take the files generated by Hugo (i.e. HTML+CSS+JS) and alter them to your wish.

Hope this helps and please let me know if you need anything else.

Cheers

**Comment by htr3n** [comment]
I will close this issue for now. Please feel free to reopen it or ask further questions in case you need help.
