### ISSUE TITLE
Dates show up incorrectly within posts

### ISSUE THREAD

**Issue by jdayton3** [htr3n/hyde-hyde#2]
When I create a new post, the date is displayed correctly (Mar **28**) in the [posts list](http://jdaytn.com/posts/):

![image](https://user-images.githubusercontent.com/16820980/38074096-d6ab126e-32ea-11e8-8931-16c99702c066.png)

But when I go to [the post](http://jdaytn.com/posts/testing-r-markdown/), the wrong date is shown (Mar **03**):

![image](https://user-images.githubusercontent.com/16820980/38074107-e56f05ee-32ea-11e8-9bb6-921e360790fd.png)

The same behavior occurs on @htr3n 's [blog](https://htr3n.github.io/).

**Comment by martinkaptein** [comment]
In your config.toml try changing the dateformat under `[params]` to `dateformat = "Jan 2, 2006"` (instead of "Jan 1, 2006"). For me, this fixed the issue.

**Comment by htr3n** [comment]
Thanks @jdayton3 for reporting the issue and @martinkaptein for your hints. I spent some time to look into the code and Hugo and found some interesting related issues. That is, date/time format in Hugo based on Go requires a rather smart but strange convention as mentioned [here](https://www.madboa.com/blog/2016/08/24/hugo-dateformat) and [here](https://github.com/gohugoio/hugo/issues/163). I went through the code of hyde-hyde and fixed most of them in the most recent commit. Please check it out.
