### ISSUE TITLE
Creating and using Portfolio pages

### ISSUE THREAD

**Issue by scotusnotes** [htr3n/hyde-hyde#20]
Can you give a short guide to using the functionality of the Portfolio items?

**Comment by htr3n** [comment]
Hi @scotusnotes,

I'm working on it, will let you know when it is done. Thanks.

**Comment by htr3n** [comment]
@scotusnotes : Here you go: https://github.com/htr3n/hyde-hyde#portfolio.

Please let me know if you have any problems. 

Cheers,
Huy

**Comment by htr3n** [comment]
I will close this issue for now as it has been resolved. Please reopen or follow up with further questions as you wish.

**Comment by scotusnotes** [comment]
Hi @htr3n 

Thank you so much for your guide! 

I thought I was doing what you suggest, but Hugo was not recognising the portfolio files. With the help of your instructions I'll check this out to find where I have gone wrong, and will certainly let you know the result.

Greetings from Berlin
Francis Sim
