### ISSUE TITLE
Sidebar Width & Flow

### ISSUE THREAD

**Issue by nberglund** [htr3n/hyde-hyde#25]
Hi guys,
Not so much an issue, more a couple of questions:
1. I cannot for the life of me find out where to change/set the width of the sidebar? 
2. Likewise, how do I get the sidebar to scroll. In the "old" Hyde theme on Jekyll there was an `overflow`  "property". 

Thank You!

Niels

**Comment by htr3n** [comment]
Hi @nberglund ,

Thanks for your questions. There are, unfortunately, no options in `config.toml` to configure these.  You need to alter the CSS/SCSSs.

1. Look at the `width` property of `.sidebar`

https://github.com/htr3n/hyde-hyde/blob/05f769fbbc9a5447622a76c0b338d57ed90b4305/static-src/scss/hyde-hyde/_responsive.scss#L28

https://github.com/htr3n/hyde-hyde/blob/05f769fbbc9a5447622a76c0b338d57ed90b4305/static/css/hyde-hyde.css#L525

2. In the same way, you can add property `overflow: scroll;` to `.sidebar` to achieve scrolling.

Hope this helps,
htr3n

**Comment by nberglund** [comment]
Hi @htr3n,

Thank you so much! Works like a charm!!

I am closing the issue (which was not an issue :) )
