### ISSUE TITLE
<!--more-->   dose not work at .Rmd

### ISSUE THREAD

**Issue by TonyFly3000** [htr3n/hyde-hyde#30]
dose not work at .Rmd  for theme hyde-hyde
same as 
https://github.com/rstudio/blogdown/issues/21

it can be slightly modified in .md documents by adding a  tag below content you wish to be included. This tag doesn't seem to work on blogdown-generated .Rmd files, causing the default summary to be the first 70 words of the post (which often includes the table of contents and other materials that aren't appropriate for a summary).

**Comment by htr3n** [comment]
@TonyFly3000 : I added support for `.Description`

https://github.com/htr3n/hyde-hyde/commit/6821a0e0e131e409e28b00a6f4321a2b42582304

**Comment by TonyFly3000** [comment]
Thanks a lot for your reply and nice theme . 
I  I found out that  work on .Rmarkdown .for now I may just use .Rmarkdown instead of .Rmd

Hugo provides the built-in .Summary function. 
in .Rmd file I added summary ,but it still show first 70 words of the post (which often includes the table of contents and other materials that aren't appropriate for a summary):

.Rmd file
---
title: test002
author: ''
date: '2018-08-30'
slug: test002
categories: []
tags: []
lastmod: '2018-08-30T01:24:02+08:00'
layout: post
type: post
highlight: no
summary: 'Its a summary'
---

**Comment by htr3n** [comment]
@TonyFly3000 : It should be `description` instead of `summary` in the front-matter.

**Comment by htr3n** [comment]
@TonyFly3000 : I meant the `index.html` for the home page, not the `list.html` for the list of posts ;)

If you want to manually control the _summary part_, please use `description` in the front matter as you mentioned. Remember to update to the newest commits of `hyde-hyde` in which I added `.Description` as above.

**Comment by TonyFly3000** [comment]
@htr3n  Problem solved !!!!!!!!!!! thanks a lot .
