### ISSUE TITLE
Main page does not display post summaries

### ISSUE THREAD

**Issue by kode54** [htr3n/hyde-hyde#39]
I have configured my blog of posts exported from a WordPress site, with a configuration file almost identical to your site's.

When I use your theme with the example site, it generates a summaries page. When I use it with my own site, it generates a sidebar, but no summaries.

I can share access to a private Git repository of the site content, if necessary to diagnose.

**Comment by htr3n** [comment]
@kode54 : I'm not sure where the problems are. If the `exampleSite` is working fine whilst yours is not, then it is likely that there are some issues with your configuration or posts.

a) Please check again the folder name under `content` whether it is `posts` as Hugo will derive the content type out of that.

The code where the posts are retrieved and listed is in `layouts/index.html`

```html
{{ $paginator := .Paginate (where .Data.Pages "Type" "posts") }}
{{ range $paginator.Pages }}
...
{{ end }}
```

b) Please check the front matter of your posts to make sure there are no strange `type` parameter.

**Comment by kode54** [comment]
The folder under `content` is `posts`, and there is nothing under my root `layouts` folder. Also, all of the `posts` have `type: post`, except for one, which I turned into a `type: page`, but that didn't stop it from appearing in the `/posts/` index listing.

**Comment by htr3n** [comment]
`index.html` is under `themes/hyde-hyde/layouts/` as we are talking about `hyde-hyde`.

**Comment by kode54** [comment]
Yeah, that fixes all of the posts I wanted displayed on the main index. Thanks.

**Comment by htr3n** [comment]
@kode54 : Yeah, it's Hugo's convention and sometimes confusing though ;) Glad it works for your site.

**Comment by Anu-kriti** [comment]
I am also facing the similar issue.. I am unable to see the summary in my homepage. content/post folder is completely blank in my case. I generated html file of all rmd in content and pasted there still that didnt work.. the layout/index.html also seems fine with same as what I have in examplesite layout
plus the contact option I cant see in disqus, its saying some error in loading that
any idea what should i do here?
