### ISSUE TITLE
function "newScratch" not defined

### ISSUE THREAD

**Issue by ansin218** [htr3n/hyde-hyde#40]
I am new to Hugo and was following the guide on this page: https://gohugo.io/getting-started/quick-start/

It seems to be working all fine. Later, I changed my theme to hyde from this repository and I encounter this error below on running hugo server: 

> ankurs@ankur-pc:~/Playground/hugo-blog-test/quickstart$ hugo server -D
> Building sites … ERROR 2018/09/21 20:28:18 Failed to add template "theme/partials/highlight-js.html" in path "/home/ankurs/Playground/hugo-blog-test/quickstart/themes/hyde-hyde/layouts/partials/highlight-js.html": template: theme/partials/highlight-js.html:3: function "newScratch" not defined
> ERROR 2018/09/21 20:28:19 Failed to add template "theme/shortcodes/fig.html" in path "/home/ankurs/Playground/hugo-blog-test/quickstart/themes/hyde-hyde/layouts/shortcodes/fig.html":template: theme/shortcodes/fig.html:1: function "newScratch" not defined
> ERROR 2018/09/21 20:28:19 theme/partials/highlight-js.html : template: theme/partials/highlight-js.html:3: function "newScratch" not defined
> ERROR 2018/09/21 20:28:19 theme/shortcodes/fig.html : template: theme/shortcodes/fig.html:1: function "newScratch" not defined
> Total in 59 ms
> Error: Error building site: logged 4 error(s) 
 
I am not able to quite get my head around this, been quite a while already. Can someone help me here? I am on Ubuntu 18.04 LTS if that matters.

**Comment by htr3n** [comment]
@ansin218 Would you mind to share your Hugo version? Or perhaps try to upgrade to the newest Hugo? `newScratch` is the work-around in Hugo 0.43+ for Go's variable scoping.

**Comment by ansin218** [comment]
I am running 0.48. Here is what I get when I run the hugo version command: 

`Hugo Static Site Generator v0.48 linux/amd64 BuildDate: 2018-08-29T06:33:51Z`

**Comment by htr3n** [comment]
It's very strange as I can compile normally with Hugo 0.48 in macOS. If reinstalling Hugo does not help, I guess you should report a bug to Hugo.

**Comment by htr3n** [comment]
@ansin218 I replace `newScratch` with the old school `Scratch` in Hugo, hopefully it works with Hugo before 0.43. Please try out the newest commit.

https://github.com/htr3n/hyde-hyde/commit/49c9ca6ffe8471446f626ee194478aadb1d4a4fb

**Comment by htr3n** [comment]
@ansin218 As I did not hear from you so far, I will close this issue for now. Please feel free to reopen it in case you would like to follow up.

**Comment by ansin218** [comment]
@htr3n Just got time to check it. It works, thank you :)
