### ISSUE TITLE
Set "about" page or "portfolio" page to default page? 

### ISSUE THREAD

**Issue by programmingforthepuzzled** [htr3n/hyde-hyde#44]
I'm pretty new to Hugo. Is it possible to make the about page or the portfolio the default page the user sees when they visit the website?

**Comment by htr3n** [comment]
@programmingforthepuzzled there might be a theme supports configuration that way but `hyde-hyde` unfortunately does not.

If I understand correctly, you want a different home page with either biography or portfolio? 

That would need you to study a bit about [Hugo lookup order](https://gohugo.io/templates/lookup-order) (i.e. which files Hugo will look for when handle a Markdown file or home page).

Then you can either replace `layouts/index.html` with relevant content of the about or portfolio page.

**Comment by htr3n** [comment]
I close this issue for now as it seems inactive. Please feel free to reopen any time.
