### ISSUE TITLE
Your theme's demo is not working on the Hugo Themes website.

### ISSUE THREAD

**Issue by onedrawingperday** [htr3n/hyde-hyde#53]
Hello @htr3n 

I saw in your theme's README that since version 0.2 the main styles were refactored and redeveloped using SCSS. 

However you have not committed the generated resources of your theme and as a result your theme's demo [fails to generate on the Hugo website](https://themes.gohugo.io/hyde-hyde/).

To fix this issue please have a look at the updated README of Hugo Themes: https://github.com/gohugoio/hugoThemes#resources You need to commit the `/resources/` directory and its contents in your theme's repository.

If you have any questions do not hesitate to ask me or @digitalcraftsman

**Comment by htr3n** [comment]
@onedrawingperday I have just fixed `hyde-hyde` by adding `resource` per the guide that you referred. I hope the demo works fine now. Please let me know if anything else need to fix too. Thanks a lot for your time and effort.

**Comment by onedrawingperday** [comment]
@htr3n I has a look at commit https://github.com/htr3n/hyde-hyde/commit/56d21df3511c8167ec57a195c2fbd303afc30992 and the associated PR.

First of all you need to commit the generated CSS for all HTML templates, meaning that locally you will have to enable all conditionals.

Second for your Hugo Pipes Assets you need to use `.RelPermalink` in your templates and you need to replace all instances of `.Permalink` see: https://github.com/gohugoio/hugoThemes#common-permalink-issues

PS I see that you just made a new commit but the Resources will be missing from your Demo because as I said above you need to use `.RelPermalink` in the templates.

**Comment by htr3n** [comment]
@onedrawingperday I've just realized the issues right after committing ;) I'm working on it. Thanks.

**Comment by htr3n** [comment]
@onedrawingperday: I fixed the templates with `.RelPermalink` and even cloned the hugoTheme Github repos to test `hyde-hyde`. The demo seems to work now. 

Please let me know if there are still some issues. Thanks for your patience.

**Comment by onedrawingperday** [comment]
@htr3n Thank you very much! I confirm the fix.

The demo will work again the next time themes are updated on the Hugo website.

CC / @digitalcraftsman
