### ISSUE TITLE
Failed to find a valid digest in the 'integrity' attribute for resource

### ISSUE THREAD

**Issue by quanhua92** [htr3n/hyde-hyde#65]
Hi,
I have the problem with 'integrity' of the css files. These are the errors that i found in the browser console.

![integrity](https://user-images.githubusercontent.com/8372557/52843094-a30ad500-3133-11e9-8821-0059af6d4794.JPG)

I found a Github issue https://github.com/alanorth/hugo-theme-bootstrap4-blog/issues/53 about this. I also use Windows so the problem may be the same as that issue.

I can solve the problem by removing the `integrity` attributes in the `styles.html`. However, I wonder if this is good or not.

What do you think about this?

**Comment by htr3n** [comment]
@quanhua92 Thanks for reporting this issue. Unfortunately, I don't have a Windows box to check whether it is a Windows-only issue.

The integrity is used to check whether the CSS is unexpectedly manipulated. For less critical and static generated web sites, it might not be so necessary.

**Comment by seanalexander** [comment]
On windows, when you checkout files, it changes the new lines from \n to \r\n, invaliding the checksum.

**Comment by nekr0z** [comment]
> On windows, when you checkout files, it changes the new lines from \n to \r\n, invaliding the checksum.

That's Git [trying to be helpful](https://adaptivepatchwork.com/2012/03/01/mind-the-end-of-your-line/#:~:text=eol%20%3D%20crlf%20When%20Git%20needs,to%20denote%20end%20of%20line.), nothing wrong with the theme itself.
