### ISSUE TITLE
author image can't display

### ISSUE THREAD

**Issue by luochang212** [htr3n/hyde-hyde#72]
Author image can't display when I deployed it. But it can display on Hugo local server when I open http://localhost:1313. I think some things might be wrong in the layout folder. By the way, I fix it by changing the theme version to v2.0.2.

**Comment by luochang212** [comment]
I change some codes in hyde-hyde\layouts\partials\sidebar.html and now it can work.

**Comment by htr3n** [comment]
@luochang212 thanks for your feedbacks.

**Comment by jadia** [comment]
I have the same issue. 
> config.toml  
```
baseURL = "https://example.com/"
authorimage = "/images/myPicture.jpeg"
```
Works fine on local Hugo server. But on Netlify the URL to author image becomes: `https://example.comimages/myPicture.jpeg`

I tried making `authorimage = "images/myPicture.jpeg"` but there was no effect. 

@luochang212  What were the fixes you made in the sidebar.html.
@htr3n Is there any fix for this that you know of? 

Thank you

**Comment by jadia** [comment]
Anyone else who is having the same issue, I fixed it by removing ` | replaceRE "^(/)+(.*)" "$2"` at line 18 in `layouts/partials/sidebar.html`.

**Comment by rucko24** [comment]
@jadia thanks a lot.
