### ISSUE TITLE
Highlighted code block positioned strangely

### ISSUE THREAD

**Issue by lwasyl** [htr3n/hyde-hyde#73]
Is there any more configuration required to configure code blocks properly (with highlight.js)? I have a very simple page which after rendering looks like this:

![image](https://user-images.githubusercontent.com/3951580/58387555-a1915880-8010-11e9-9dd5-ebffb1cbcca7.png)

The HTML seems correct (I think):
```html
<div class="post">
<div class="paragraph">
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation</p>
</div>
<div class="listingblock">
<div class="content">
<pre class="highlightjs highlight"><code data-lang="kotlin" class="language-kotlin hljs">public suspend fun ddd() {
    return@ddd Unit
}
```

I haven't used any custom configuration, just `highlightjs = true` in the `config.toml` file under `[params]`. Note that when I change highligh style I do get different styles (e.g. dark background with `monokai` style. It's just the code block position and width that are completely off. Am I doing something wrong, missing something obvious?

**Comment by htr3n** [comment]
@lwasyl Please refer to the [Options](https://github.com/htr3n/hyde-hyde#options) part in the README. Perhaps you would need to add `highlightjslanguages = ["kotlin"]` to the preample of your Markdown file.

**Comment by lwasyl** [comment]
Actually I figured out there's some difference in how HTML is generated for Markdown and AsiiDoc (which I've been wanting to use). Here's how the page looks for AsciiDoc:
![image](https://user-images.githubusercontent.com/3951580/58780676-f2d5b500-85d9-11e9-9de7-408ac9dd1a95.png)

And here's regular markdown:
![image](https://user-images.githubusercontent.com/3951580/58780705-08e37580-85da-11e9-875e-8daec6bc7414.png)

However I don't know enough about Hugo or web development to tell whether it's something reasonable to fix either in the theme or by myself locally (and where to even start). I'd appreciate any input

**Comment by htr3n** [comment]
@lwasyl Not sure whether I got what you meant here. I don't use AsciiDoc and have no knowledge of Hugo parser for AsciiDoc, so I might not be able to advise furthermore on this matter.

**Comment by lwasyl** [comment]
It's just that AsciiDoc apparently produces different HTML. It's supported by Hugo as an external tool, and I'm wondering whether it's reasonable to add support for asciidoc in the theme. If not, feel free to close the issue.

**Comment by htr3n** [comment]
@lwasyl AsciiDoc is a content format supported by Hugo via external tools, thus, it's irrelevant to the theme (any theme, not only `hyde-hyde`). So I guess it does not make any sense to "support" AsciiDoc with `hyde-hyde` (whatever that means).

Perhaps the differences you spotted are due to the external tools whilst the transforming of Markdown to HTML is internal to Hugo.
