### ISSUE TITLE
GitLab tocss error

### ISSUE THREAD

**Issue by gVallverdu** [htr3n/hyde-hyde#75]
Hi,

Using the hyde-hyde theme on gitlab pages, I got an error if I try to add toc in my posts.

Here is the message:

```
Submodule 'themes/hyde-hyde' (https://github.com/htr3n/hyde-hyde.git) registered for path 'themes/hyde-hyde'
Cloning into '/builds/gsalvatovallverdu/gsalvatovallverdu.gitlab.io/themes/hyde-hyde'...
Submodule path 'themes/hyde-hyde': checked out '3551425f3f3f8044ff541113075537583f485c8c'
Entering 'themes/hyde-hyde'
$ hugo
Building sites … ERROR 2019/05/29 07:47:46 error: failed to transform resource: TOCSS: failed to transform "scss/hugo-toc.scss" (text/x-scss): this feature is not available in your current Hugo version, see https://goo.gl/YMrWcn for more information
Total in 80 ms
Error: Error building site: logged 1 error(s)
ERROR: Job failed: exit code 255
```

The error disappear if I remove the toc, that is if I do not set this variable in `config.toml`.

Locally, it works. I run hugo version 0.55.6. It seems, gitlab use version 56 or higher (later).

**Comment by gVallverdu** [comment]
Actually you need the extended version of hugo.

Thus in the `.gitlab-ci.yml` it is necessary to set:

```yml
image: registry.gitlab.com/pages/hugo/hugo_extended:latest
```

May be you could drop this somewhere in the doc ?

**Comment by htr3n** [comment]
@gVallverdu Thanks for your feedbacks. I have not tried to host with gitlab but many would benefit from your advices. Nonetheless, I would rather keep `hyde-hyde` documentatation neutral and minimal, and thus, leave your information here in the "Issues" part so that anyone can look it up when needed.
