### ISSUE TITLE
[Question] Navigate to start page in mobile

### ISSUE THREAD

**Issue by Auo** [htr3n/hyde-hyde#88]
Hi

It doesn't seem to be possible to navigate back to the start page on mobile.

On desktop you can click the `Title` to navigate back to the start page, but it's not the same behaviour on mobile.

Is this the intended behaviour? If that is the case what is the recomended solution to navigate back to the start page? 

Thanks!

**Comment by htr3n** [comment]
@Auo sorry to be late. I'm aware that the behaviors are different. The mobile version facilitates a collapsible menu using CSS so that clicking the `title` will trigger the menu. You can change that but you may loose the CSS collapsible menu.
