### ISSUE TITLE
Home lists projects instead of posts when number_of_posts < number_of_projects

### ISSUE THREAD

**Issue by MarcoIeni** [htr3n/hyde-hyde#93]
When there are less posts then projects, home page lists items belonging to portfolio instead of posts.

For example from the example site I deleted all posts except "creating a new theme" and "migrate from jekyll".
If I restart the server, portfolio items are displayed.

I don't know if it is the intended behavior, but for me it's confusing. At least it should be specified in the readme how to always show posts.

A method was expalined in issue #19, but code has changed, so it's no longer valid.
In my opinion it should be explained in the documentation.

**Comment by MarcoIeni** [comment]
The problem is of course in file layouts/index.html.

For what I understood, the value of the variable `site.Params.mainSections` will be "portfolio" if you have more projects than posts. So this variable cannot be used.

[This](https://github.com/MarcoIeni/hyde-hyde/commit/89630a412ee808b9cda9a510b158abc6b0fa99a3) is my solution. I know you may not want to hardcode those values in the theme's code.

**Comment by nekr0z** [comment]
> For what I understood, the value of the variable `site.Params.mainSections` will be "portfolio" if you have more projects than posts.

Exactly. As [expected](https://gohugo.io/functions/where/#mainsections), actually. So the proper solution is to define your own mainSections in `config.toml`.

**Comment by MarcoIeni** [comment]
Ok, thanks.
Maybe this could be clarified in the README?
Otherwise we can close this issue.

**Comment by nekr0z** [comment]
> Maybe this could be clarified in the README?

Yeah, I agree, it's a little bit obscure. But then again, one can argue that users of the theme are expected to read `hugo`'s documentation in addition to the theme's `README`.

Anyway, if I were @htr3n I would accept a pull request that documented this particular caveat in the `README`. Care to create one? ;)

**Comment by htr3n** [comment]
I haven't had time to follow up all recent Hugo versions, still use oldie Hugo that works fine for me so far. The changes @nekr0z mentioned, I think, are in newer Hugo, aren't they? Before, there are not so many options apart from checking the type of posts. Perhaps the developers listened to the community and created those nice features. I can incorporate the new features when I have some spare time from work, currently totally underwater. Nonetheless, any PRs are appreciated.

**Comment by MarcoIeni** [comment]
I close this since it was solved in #113
