### ISSUE TITLE
Where are favicon settings and file located?

### ISSUE THREAD

**Issue by thisisjaymedina** [htr3n/hyde-hyde#94]
Hi there, thanks for your theme! I was trying to change the favicon from the "H" to something else, but can't seem to find where the setting of the favicon is located, or even where the favicon file is even located.

Any help and information you'd be able to share would be much appreciated. Thanks!

**Comment by MarcoIeni** [comment]
If you want to change the H with your avatar, you can add this options into config.toml:

```
[params]
    authorimage = "/img/avatar.jpg"
```
You put avatar.jpg under /static/img/

The current H is memorized in /exampleSite/static/img/hugo.png

**Comment by MarcoIeni** [comment]
If you want another site example in addition to the provided one, you can check out the website of the author of this theme:
https://htr3n.github.io/
https://github.com/htr3n/htr3n-blog

**Comment by thisisjaymedina** [comment]
Thank you for the info, but that's where to set the author image for the sidebar, which I've already been able to set. I'm looking for the favicon setting for the small icon that appears in the browser tab. I've attached a screenshot to better explain what I mean...

![Screenshot_2019-11-09_17-19-14](https://user-images.githubusercontent.com/48869130/68536232-2d741400-0315-11ea-97f9-54fb61aa5151.png)

**Comment by MarcoIeni** [comment]
Ok, now I know what favicon means ^^'

Anyway, in file layouts/partials/header.html there is a reference to the path /favicon.png.

I tried to put a 16x16 icon (generated with [this](https://favicon.io/) nice website) in the path /static/favicon.png and it works :+1:

**Comment by thisisjaymedina** [comment]
Hi Marcoleni,

Thank you so very much for this information. This works perfectly!
