### ISSUE TITLE
Optionally make links open in a new browser tab?

### ISSUE THREAD

**Issue by metawops** [htr3n/hyde-hyde#97]
How would I add a new boolean parameter for my config.toml file of my hugo blog that would switch between (all) links opening in a new browser tab (```target="_blank"```) or in the same tab? 😳

**Comment by sandipb** [comment]
This is not pretty, and I am pretty sure the effect is not what you want.

But if you put this in `/layouts/partials/header/custom.html`, it will open *every* link in a new tab. Even the post title links! It works. I tried it.

```html
<base target="_blank">
```
Ref: https://stackoverflow.com/a/24428525/390514

**Comment by htr3n** [comment]
@metawops Yeah, @sandipb is right, this is mostly about HTML than `hyde-hyde` specific. Just set the `<base target...>` and you are good to go.
