### ISSUE TITLE
Configure toc as initially closed?

### ISSUE THREAD

**Issue by metawops** [htr3n/hyde-hyde#98]
Is there a way to configure the table of content (hugo mode, i.e. ```toc = "hugo"``` in the config.toml file) in a way that it is not opened but closed initially? 😳

**Comment by htr3n** [comment]
@metawops That option would be nice to have, unfortunately, I haven't had enough time to develop further on. It's essentially quite straightforward but rather requires extra effort for different supported TOC libraries.
E.g. per Hugo document

> The built-in .TableOfContents variables outputs a <nav id="TableOfContents"> element with a child <ul>, whose child <li> elements begin with appropriate HTML headings. See the available settings to configure what heading levels you want to include in TOC.

As such, you can insert a short JavaScript or so to set the element with id `TableOfContents` to collapse instead.

Unfortunately, there are no consensus among different libraries, each must be dealt with on per-case basis.
